### ISSUE TITLE
Got an issue when try use livehosts

### ISSUE THREAD

**Issue by Tetsu2804** [Aioros/livehosts#11]
Hi Aioros,

I have an issue when try use livehosts to change file etc on my machine 
![livehostsissue2](https://user-images.githubusercontent.com/92264620/158509986-fb7d82ec-13e3-45e4-b785-63c505770d1d.jpg)
![livehostsissue1](https://user-images.githubusercontent.com/92264620/158509993-2a55d00f-2656-41bf-9026-a5d94625658d.PNG)

Could you help me to check it ,

Thank you,
Tuan Anh

**Comment by Aioros** [comment]
Hey @TranNguyenTuanAnh , version 2.0 of the extension has just been published on the Chrome Web Store. Let me know if you have any issues with it after updating. I'm closing this one for now, but feel free to open a new issue if that's the case.
