### ISSUE TITLE
Make version of LiveHosts extension for Mozilla Firefox browser

### ISSUE THREAD

**Issue by MurzNN** [Aioros/livehosts#3]
Mozilla Firefox provide WebExtensions API, that is compatible with Google Chrome, so many extensions use same code base for both platforms: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions

Can you lookup Mozilla API and make your extension compatible with Mozilla Firefox? Thanks!

**Comment by Aioros** [comment]
You're absolutely right, and I planned on making a Firefox version, but I didn't have the time. I'll get on that as soon as I can.

**Comment by Aioros** [comment]
I started working on a Firefox-compatible version of the extension. It hasn't been tested extensively yet, but you can find a [v1.1.1 release for Firefox here](https://github.com/Aioros/livehosts/releases/tag/v1.1.1-firefox) for now. I will submit it to AMO after a few tests.

**Comment by Aioros** [comment]
Published a (tentative) first version at https://addons.mozilla.org/en-US/firefox/addon/livehosts/. I'll close this issue, please open a new one for any problems the Firefox version might have.
